# Generated by Django 5.0.2 on 2024-03-01 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('AuthorEmail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AuthorEmail', models.EmailField(max_length=254)),
                ('courseName', models.CharField(max_length=120)),
                ('about', models.TextField()),
                ('prices', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('minStudents', models.IntegerField()),
                ('maxStudents', models.IntegerField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.author')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('courses', models.ManyToManyField(to='courses.course')),
            ],
        ),
    ]
